import { GrantProposal, VulnerabilityBounty, GovProposal, ThreatAdvisory, TreasuryAllocation } from '../types/ngo';

export const MOCK_GRANTS: GrantProposal[] = [
  {
    id: 'GRANT-2026-081',
    title: 'Post-Quantum TLS 1.3 Implementation for OpenSSL Ecosystem',
    applicant: 'QuantumDefense Research Lab',
    category: 'Cryptographic Research',
    amountRequested: '$150,000',
    status: 'Milestone 2/3',
    quadraticContributors: 412,
    tags: ['Kyber-1024', 'Dilithium', 'TLS 1.3', 'PQC'],
    description: 'Upgrading open-source core web TLS transport libraries with NIST-standardized Kyber lattice key encapsulation algorithms.',
    impactScore: 98,
  },
  {
    id: 'GRANT-2026-074',
    title: 'Zero-Knowledge Proof Audit Engine for Enclave Memory Integrity',
    applicant: 'ZKP Guard Collective',
    category: 'Auditing & Verification',
    amountRequested: '$95,000',
    status: 'Active Round',
    quadraticContributors: 620,
    tags: ['SGX', 'STARKs', 'Memory-Safety', 'Rust'],
    description: 'Succinct zero-knowledge verification framework allowing public attestation of enclave key state without exposing raw secrets.',
    impactScore: 94,
  },
  {
    id: 'GRANT-2026-069',
    title: 'eBPF-Based Real-Time Container Threat Detection Agent',
    applicant: 'KernelShield Foundation',
    category: 'Defensive Tooling',
    amountRequested: '$110,000',
    status: 'Completed',
    quadraticContributors: 318,
    tags: ['Linux', 'eBPF', 'Kernel', 'Runtime-Security'],
    description: 'Lightweight kernel-level agent detecting zero-day syscall anomalies in Kubernetes clusters with microsecond overhead.',
    impactScore: 96,
  },
  {
    id: 'GRANT-2026-052',
    title: 'Global Open-Source Dependency Vulnerability Graph (OSDV)',
    applicant: 'OpenSupply Chain Alliance',
    category: 'Infrastructure Defense',
    amountRequested: '$200,000',
    status: 'Milestone 2/3',
    quadraticContributors: 845,
    tags: ['Supply-Chain', 'SBOM', 'GraphDB', 'CVE'],
    description: 'Decentralized index mapping upstream supply chain compromise paths across PyPI, Cargo, and npm ecosystems.',
    impactScore: 99,
  },
];

export const MOCK_BOUNTIES: VulnerabilityBounty[] = [
  {
    id: 'VULN-9021',
    cveId: 'CVE-2026-38291',
    title: 'Buffer Overread in Hardware Security Enclave Mailbox Protocol',
    targetProject: 'OpenEnclave OS Core',
    severity: 'Critical',
    rewardPool: '$50,000',
    status: 'Patched',
    disclosedDate: '2026-08-14',
    reporter: 'alice_sec',
  },
  {
    id: 'VULN-8842',
    cveId: 'CVE-2026-29104',
    title: 'Timing Side-Channel Leakage in Edwards Curve Scalar Multiplication',
    targetProject: 'LibSodium PQC Branch',
    severity: 'High',
    rewardPool: '$25,000',
    status: 'Open Bounty',
    disclosedDate: '2026-08-20',
    reporter: 'crypt0_ninja',
  },
  {
    id: 'VULN-8710',
    title: 'Unsanitized Descriptor Leakage in Microkernel IPC Layer',
    targetProject: 'seL4 Microkernel Distro',
    severity: 'Medium',
    rewardPool: '$12,000',
    status: 'Under Audit',
    disclosedDate: '2026-08-22',
    reporter: 'kernel_bug_hunter',
  },
  {
    id: 'VULN-8603',
    cveId: 'CVE-2026-11849',
    title: 'Remote Integer Overflow in DNSSEC Validator Parser',
    targetProject: 'Public Resolver Engine',
    severity: 'Critical',
    rewardPool: '$75,000',
    status: 'Patched',
    disclosedDate: '2026-07-29',
    reporter: 'shadow_auditor',
  },
];

export const MOCK_PROPOSALS: GovProposal[] = [
  {
    id: 'NGOP-2026-12',
    title: 'Allocate $500,000 Treasury Matching Pool for Retroactive Public Goods Funding (RPGF Round 4)',
    sigGroup: 'SIG-01 Infrastructure',
    author: 'Elena Rostova (Council Member)',
    status: 'Active Voting',
    votesFor: 18450,
    votesAgainst: 1200,
    endsInDays: 3,
    summary: 'Distributing retroactive rewards to open-source maintainers of critical cryptographic libraries based on community impact scores.',
  },
  {
    id: 'NGOP-2026-11',
    title: 'Establish Mandatory Formal Verification Standard for High-Assurance Security Enclaves',
    sigGroup: 'SIG-02 Crypto & Privacy',
    author: 'Dr. Marcus Vance (Research Director)',
    status: 'Passed',
    votesFor: 24100,
    votesAgainst: 850,
    endsInDays: 0,
    summary: 'Requiring zero-knowledge mathematical correctness proofs for all enclave firmware funded through NGO Tier-1 grants.',
  },
  {
    id: 'NGOP-2026-10',
    title: 'Expand Emergency Incident Response Guild (EIRG) SLA to 24/7 Global On-Call Coverage',
    sigGroup: 'SIG-03 Rapid Defense',
    author: 'Kaito Tanaka (SecOps Lead)',
    status: 'Executed',
    votesFor: 19800,
    votesAgainst: 3400,
    endsInDays: 0,
    summary: 'Deploying round-the-clock incident containment teams for critical infrastructure open-source projects under active attack.',
  },
];

export const MOCK_ADVISORIES: ThreatAdvisory[] = [
  {
    id: 'ADV-2026-089',
    timestamp: '10:14 AM UTC',
    severity: 'Critical',
    title: 'Zero-Day RCE Exploit in Edge Proxy Parse Logic',
    affectedComponent: 'Envoy / NGINX Mod',
    mitigationStatus: 'Patch Released',
  },
  {
    id: 'ADV-2026-088',
    timestamp: 'Yesterday',
    severity: 'High',
    title: 'Active Exploitation of Weak Entropy Generators in Embedded IoT Enclaves',
    affectedComponent: 'Hardware RNG Driver',
    mitigationStatus: 'Workaround Available',
  },
  {
    id: 'ADV-2026-087',
    timestamp: '2 Days Ago',
    severity: 'Medium',
    title: 'Malicious Dependency Injection Campaign targeting Rust Cargo Ecosystem',
    affectedComponent: 'Crates.io Registry',
    mitigationStatus: 'Investigation',
  },
];

export const MOCK_TREASURY: TreasuryAllocation[] = [
  { name: 'Open Source Security Grants', amountUsd: 14200000, percentage: 42, color: '#10b981' },
  { name: 'Vulnerability Bounty Reserve', amountUsd: 8500000, percentage: 25, color: '#06b6d4' },
  { name: 'Emergency Incident Defense Fund', amountUsd: 5100000, percentage: 15, color: '#6366f1' },
  { name: 'Research & Formal Audits', amountUsd: 4080000, percentage: 12, color: '#8b5cf6' },
  { name: 'Operations & Global Chapters', amountUsd: 2040000, percentage: 6, color: '#f59e0b' },
];
